// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.7.1.0
//      SpecFlow Generator Version:1.7.0.0
//      Runtime Version:4.0.30319.239
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace NBlog.Specs.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.7.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Post creation and editing")]
    public partial class PostCreationAndEditingFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "PostFeatures.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Post creation and editing", "In order to show user blog posts\r\nAs a logged in user\r\nI should be able to create" +
                    " and edit posts", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Create post")]
        [NUnit.Framework.CategoryAttribute("NoPosts")]
        [NUnit.Framework.CategoryAttribute("Authenticated")]
        public virtual void CreatePost()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create post", new string[] {
                        "NoPosts",
                        "Authenticated"});
#line 8
this.ScenarioSetup(scenarioInfo);
#line 9
 testRunner.Given("I am on the \"create post page\"");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "InputField",
                        "DataType",
                        "Input"});
            table1.AddRow(new string[] {
                        "Title",
                        "string",
                        "Demo title"});
            table1.AddRow(new string[] {
                        "ShortUrl",
                        "longstring",
                        "demopost"});
            table1.AddRow(new string[] {
                        "Content",
                        "string",
                        "Demo content"});
            table1.AddRow(new string[] {
                        "Excerpt",
                        "string",
                        "This is the excerpt"});
            table1.AddRow(new string[] {
                        "Tags",
                        "string",
                        "tag1, tag2"});
            table1.AddRow(new string[] {
                        "Categories",
                        "string",
                        "cat1, cat2"});
#line 10
 testRunner.When("I enter the following information", ((string)(null)), table1);
#line 18
 testRunner.And("I click the \"save\" button");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "ShortUrl",
                        "PublishDate",
                        "Excerpt",
                        "Tags",
                        "Categories",
                        "LastUpdateDate"});
            table2.AddRow(new string[] {
                        "demopost",
                        "Today",
                        "This is the excerpt",
                        "tag1, tag2",
                        "cat1, cat2",
                        "Today"});
#line 19
 testRunner.Then("a post with the following meta data should have been created", ((string)(null)), table2);
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Title",
                        "Content",
                        "SaveDate"});
            table3.AddRow(new string[] {
                        "Demot title",
                        "Demo content",
                        "Today"});
#line 22
 testRunner.And("the following post versions", ((string)(null)), table3);
#line 25
 testRunner.And("I should see a success message");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Create and publish post")]
        [NUnit.Framework.CategoryAttribute("NoPosts")]
        [NUnit.Framework.CategoryAttribute("Authenticated")]
        public virtual void CreateAndPublishPost()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create and publish post", new string[] {
                        "NoPosts",
                        "Authenticated"});
#line 29
this.ScenarioSetup(scenarioInfo);
#line 30
 testRunner.Given("I am on the \"create post page\"");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "InputField",
                        "DataType",
                        "Input"});
            table4.AddRow(new string[] {
                        "Title",
                        "string",
                        "Demo title"});
            table4.AddRow(new string[] {
                        "ShortUrl",
                        "longstring",
                        "demopost"});
            table4.AddRow(new string[] {
                        "Content",
                        "string",
                        "Demo content"});
            table4.AddRow(new string[] {
                        "Excerpt",
                        "string",
                        "This is the excerpt"});
            table4.AddRow(new string[] {
                        "Tags",
                        "string",
                        "tag1, tag2"});
            table4.AddRow(new string[] {
                        "Categories",
                        "string",
                        "cat1, cat2"});
#line 31
 testRunner.When("I enter the following information", ((string)(null)), table4);
#line 39
 testRunner.And("I click the \"publish\" button");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "ShortUrl",
                        "PublishDate",
                        "Excerpt",
                        "Tags",
                        "Categories",
                        "LastUpdateDate"});
            table5.AddRow(new string[] {
                        "demopost",
                        "Today",
                        "This is the excerpt",
                        "tag1, tag2",
                        "cat1, cat2",
                        "Today"});
#line 40
 testRunner.Then("a post with the following meta data should have been created", ((string)(null)), table5);
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Title",
                        "Content",
                        "SaveDate"});
            table6.AddRow(new string[] {
                        "Demot title",
                        "Demo content",
                        "Today"});
#line 43
 testRunner.And("the following post versions", ((string)(null)), table6);
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Title",
                        "Content",
                        "SaveDate"});
            table7.AddRow(new string[] {
                        "Demot title",
                        "Demo content",
                        "Today"});
#line 46
 testRunner.And("with the following published post", ((string)(null)), table7);
#line 49
 testRunner.And("I should see a success message");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Create and publish post back in time")]
        [NUnit.Framework.CategoryAttribute("NoPosts")]
        [NUnit.Framework.CategoryAttribute("Authenticated")]
        public virtual void CreateAndPublishPostBackInTime()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create and publish post back in time", new string[] {
                        "NoPosts",
                        "Authenticated"});
#line 53
this.ScenarioSetup(scenarioInfo);
#line 54
 testRunner.Given("I am on the \"create post page\"");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "InputField",
                        "DataType",
                        "Input"});
            table8.AddRow(new string[] {
                        "Title",
                        "string",
                        "Demo title"});
            table8.AddRow(new string[] {
                        "ShortUrl",
                        "longstring",
                        "demopost"});
            table8.AddRow(new string[] {
                        "Content",
                        "string",
                        "Demo content"});
            table8.AddRow(new string[] {
                        "Excerpt",
                        "string",
                        "This is the excerpt"});
            table8.AddRow(new string[] {
                        "PublishDate",
                        "datetime",
                        "2011-10-01"});
            table8.AddRow(new string[] {
                        "Tags",
                        "string",
                        "tag1, tag2"});
            table8.AddRow(new string[] {
                        "Categories",
                        "string",
                        "cat1, cat2"});
#line 55
 testRunner.When("I enter the following information", ((string)(null)), table8);
#line 64
 testRunner.And("I click the \"publish\" button");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "ShortUrl",
                        "PublishDate",
                        "Excerpt",
                        "Tags",
                        "Categories",
                        "LastUpdateDate"});
            table9.AddRow(new string[] {
                        "demopost",
                        "2011-10-01",
                        "This is the excerpt",
                        "tag1, tag2",
                        "cat1, cat2",
                        "Today"});
#line 65
 testRunner.Then("a post with the following meta data should have been created", ((string)(null)), table9);
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Title",
                        "Content",
                        "SaveDate"});
            table10.AddRow(new string[] {
                        "Demot title",
                        "Demo content",
                        "Today"});
#line 68
 testRunner.And("the following post versions", ((string)(null)), table10);
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Title",
                        "Content",
                        "SaveDate"});
            table11.AddRow(new string[] {
                        "Demot title",
                        "Demo content",
                        "Today"});
#line 71
 testRunner.And("with the following published post", ((string)(null)), table11);
#line 74
 testRunner.And("I should see a success message");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Creating a post with existing short url should fail")]
        [NUnit.Framework.CategoryAttribute("NoPosts")]
        [NUnit.Framework.CategoryAttribute("Authenticated")]
        public virtual void CreatingAPostWithExistingShortUrlShouldFail()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Creating a post with existing short url should fail", new string[] {
                        "NoPosts",
                        "Authenticated"});
#line 78
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "ShortUrl",
                        "PublishDate",
                        "Excerpt",
                        "Tags",
                        "Categories",
                        "LastUpdateDate"});
            table12.AddRow(new string[] {
                        "demopost",
                        "2011-10-01",
                        "This is the excerpt",
                        "tag1, tag2",
                        "cat1, cat2",
                        "Today"});
#line 79
 testRunner.Given("a post exist with the following versions", ((string)(null)), table12);
#line 82
 testRunner.And("I am on the \"create post page\"");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "InputField",
                        "DataType",
                        "Input"});
            table13.AddRow(new string[] {
                        "Title",
                        "string",
                        "Demo title"});
            table13.AddRow(new string[] {
                        "ShortUrl",
                        "longstring",
                        "demopost"});
            table13.AddRow(new string[] {
                        "Content",
                        "string",
                        "Demo content"});
            table13.AddRow(new string[] {
                        "Excerpt",
                        "string",
                        "This is the excerpt"});
            table13.AddRow(new string[] {
                        "PublishDate",
                        "datetime",
                        "2011-10-01"});
            table13.AddRow(new string[] {
                        "Tags",
                        "string",
                        "tag1, tag2"});
            table13.AddRow(new string[] {
                        "Categories",
                        "string",
                        "cat1, cat2"});
#line 83
 testRunner.When("I enter the following information", ((string)(null)), table13);
#line 92
 testRunner.And("I click the \"save\" button");
#line 93
 testRunner.Then("I should see an error message");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "ShortUrl",
                        "PublishDate",
                        "Excerpt",
                        "Tags",
                        "Categories",
                        "LastUpdateDate"});
            table14.AddRow(new string[] {
                        "demopost",
                        "2011-10-01",
                        "This is the excerpt",
                        "tag1, tag2",
                        "cat1, cat2",
                        "Today"});
#line 94
 testRunner.And("the following post version should exist", ((string)(null)), table14);
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Updating unpublished post")]
        [NUnit.Framework.CategoryAttribute("NoPosts")]
        [NUnit.Framework.CategoryAttribute("Authenticated")]
        public virtual void UpdatingUnpublishedPost()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Updating unpublished post", new string[] {
                        "NoPosts",
                        "Authenticated"});
#line 100
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "ShortUrl",
                        "PublishDate",
                        "Excerpt",
                        "Tags",
                        "Categories",
                        "LastUpdateDate"});
            table15.AddRow(new string[] {
                        "demopost",
                        "2011-10-01",
                        "This is the excerpt",
                        "tag1, tag2",
                        "cat1, cat2",
                        "Today"});
#line 101
 testRunner.Given("the following post", ((string)(null)), table15);
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "Title",
                        "Content",
                        "SaveDate"});
            table16.AddRow(new string[] {
                        "Demo title",
                        "Demo content",
                        "2011-10-02"});
            table16.AddRow(new string[] {
                        "Demo title",
                        "Demo content1",
                        "2011-10-03"});
#line 104
 testRunner.And("the following post versions", ((string)(null)), table16);
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "Title",
                        "Content",
                        "SaveDate"});
            table17.AddRow(new string[] {
                        "Demo title",
                        "Demo content",
                        "2011-10-02"});
#line 108
 testRunner.And("with the following published post", ((string)(null)), table17);
#line 111
 testRunner.And("I am on the \"edit post page\" for \"demopost\"");
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "InputField",
                        "DataType",
                        "Input"});
            table18.AddRow(new string[] {
                        "Title",
                        "string",
                        "Demo title2"});
            table18.AddRow(new string[] {
                        "ShortUrl",
                        "longstring",
                        "demopost"});
            table18.AddRow(new string[] {
                        "Content",
                        "string",
                        "Demo content2"});
            table18.AddRow(new string[] {
                        "Excerpt",
                        "string",
                        "This is the excerpt2"});
            table18.AddRow(new string[] {
                        "PublishDate",
                        "datetime",
                        "2011-10-01"});
            table18.AddRow(new string[] {
                        "Tags",
                        "string",
                        "tag1, tag3"});
            table18.AddRow(new string[] {
                        "Categories",
                        "string",
                        "cat3, cat2"});
#line 112
 testRunner.And("I enter the following information", ((string)(null)), table18);
#line 121
 testRunner.And("I click the \"save\" button");
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "ShortUrl",
                        "PublishDate",
                        "Excerpt",
                        "Tags",
                        "Categories",
                        "LastUpdateDate"});
            table19.AddRow(new string[] {
                        "demopost",
                        "2011-10-01",
                        "This is the excerpt",
                        "tag1, tag2",
                        "cat1, cat2",
                        "Today"});
#line 122
 testRunner.Then("I should have the following post versions for post with short url \"demopost\"", ((string)(null)), table19);
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "Title",
                        "Content",
                        "SaveDate"});
            table20.AddRow(new string[] {
                        "Demo title",
                        "Demo content1",
                        "2011-10-02"});
            table20.AddRow(new string[] {
                        "Demo title2",
                        "Demo content2",
                        "Today"});
#line 125
 testRunner.And("the following post versions", ((string)(null)), table20);
#line hidden
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                        "Content",
                        "SaveDate"});
            table21.AddRow(new string[] {
                        "Demo content1",
                        "2011-10-02"});
#line 129
 testRunner.And("with the following published post", ((string)(null)), table21);
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Publishing unpublished post")]
        [NUnit.Framework.CategoryAttribute("NoPosts")]
        [NUnit.Framework.CategoryAttribute("Authenticated")]
        public virtual void PublishingUnpublishedPost()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Publishing unpublished post", new string[] {
                        "NoPosts",
                        "Authenticated"});
#line 135
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                        "ShortUrl",
                        "PublishDate",
                        "Excerpt",
                        "Tags",
                        "Categories",
                        "LastUpdateDate"});
            table22.AddRow(new string[] {
                        "demopost",
                        "2011-10-01",
                        "This is the excerpt",
                        "tag1, tag2",
                        "cat1, cat2",
                        "Today"});
#line 136
 testRunner.Given("the following post", ((string)(null)), table22);
#line hidden
            TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                        "Title",
                        "Content",
                        "SaveDate"});
            table23.AddRow(new string[] {
                        "Demo title",
                        "Demo content",
                        "2011-10-02"});
            table23.AddRow(new string[] {
                        "Demo title",
                        "Demo content1",
                        "2011-10-03"});
#line 139
 testRunner.And("the following post versions", ((string)(null)), table23);
#line hidden
            TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                        "Title",
                        "Content",
                        "SaveDate"});
            table24.AddRow(new string[] {
                        "Demo title",
                        "Demo content",
                        "2011-10-02"});
#line 143
 testRunner.And("with the following published post", ((string)(null)), table24);
#line 146
 testRunner.And("I am on the \"edit post page\" for \"demopost\"");
#line 147
 testRunner.And("I click the \"publish\" button");
#line hidden
            TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                        "ShortUrl",
                        "PublishDate",
                        "Excerpt",
                        "Tags",
                        "Categories",
                        "LastUpdateDate"});
            table25.AddRow(new string[] {
                        "demopost",
                        "2011-10-01",
                        "This is the excerpt",
                        "tag1, tag2",
                        "cat1, cat2",
                        "Today"});
#line 148
 testRunner.Then("I should have the following post versions for post with short url \"demopost\"", ((string)(null)), table25);
#line hidden
            TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                        "Title",
                        "Content",
                        "SaveDate"});
            table26.AddRow(new string[] {
                        "Demo title",
                        "Demo content",
                        "2011-10-02"});
            table26.AddRow(new string[] {
                        "Demo title",
                        "Demo content1",
                        "Today"});
#line 151
 testRunner.And("the following post versions", ((string)(null)), table26);
#line hidden
            TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                        "Title",
                        "Content",
                        "SaveDate"});
            table27.AddRow(new string[] {
                        "Demo title",
                        "Demo content1",
                        "Today"});
#line 155
 testRunner.And("with the following published post", ((string)(null)), table27);
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#endregion
