// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace NBlog.Areas.Admin.Controllers {
    public partial class PostController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected PostController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Index() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Index);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult CreateAndPublish() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.CreateAndPublish);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Edit() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Edit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Publish() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Publish);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Unpublish() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Unpublish);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PostController Actions { get { return MVC.Admin.Post; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Admin";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Post";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Post";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Index = "Index";
            public readonly string Create = "Create";
            public readonly string CreateAndPublish = "CreateAndPublish";
            public readonly string Edit = "Edit";
            public readonly string Publish = "Publish";
            public readonly string Unpublish = "Unpublish";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants {
            public const string Index = "Index";
            public const string Create = "Create";
            public const string CreateAndPublish = "CreateAndPublish";
            public const string Edit = "Edit";
            public const string Publish = "Publish";
            public const string Unpublish = "Unpublish";
        }


        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index {
            public readonly string includeDeleted = "includeDeleted";
        }
        static readonly ActionParamsClass_CreateAndPublish s_params_CreateAndPublish = new ActionParamsClass_CreateAndPublish();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CreateAndPublish CreateAndPublishParams { get { return s_params_CreateAndPublish; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CreateAndPublish {
            public readonly string command = "command";
        }
        static readonly ActionParamsClass_Edit s_params_Edit = new ActionParamsClass_Edit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Edit EditParams { get { return s_params_Edit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Edit {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Publish s_params_Publish = new ActionParamsClass_Publish();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Publish PublishParams { get { return s_params_Publish; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Publish {
            public readonly string command = "command";
        }
        static readonly ActionParamsClass_Unpublish s_params_Unpublish = new ActionParamsClass_Unpublish();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Unpublish UnpublishParams { get { return s_params_Unpublish; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Unpublish {
            public readonly string command = "command";
        }
        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string Create = "~/Areas/Admin/Views/Post/Create.cshtml";
            public readonly string Edit = "~/Areas/Admin/Views/Post/Edit.cshtml";
            public readonly string Index = "~/Areas/Admin/Views/Post/Index.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_PostController: NBlog.Areas.Admin.Controllers.PostController {
        public T4MVC_PostController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index(bool? includeDeleted) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Index);
            callInfo.RouteValueDictionary.Add("includeDeleted", includeDeleted);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Create() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Create);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Create(NBlog.Domain.Commands.CreatePostCommand command) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Create);
            callInfo.RouteValueDictionary.Add("command", command);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult CreateAndPublish(NBlog.Domain.Commands.CreateAndPublishPostCommand command) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.CreateAndPublish);
            callInfo.RouteValueDictionary.Add("command", command);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Edit(System.Guid id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Edit);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Publish(NBlog.Domain.Commands.PublishPostCommand command) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Publish);
            callInfo.RouteValueDictionary.Add("command", command);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Unpublish(NBlog.Domain.Commands.UnpublishPostCommand command) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Unpublish);
            callInfo.RouteValueDictionary.Add("command", command);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Edit(NBlog.Domain.Commands.UpdatePostCommand command) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Edit);
            callInfo.RouteValueDictionary.Add("command", command);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
